/**
 * ESLint — flat config.
 *
 * `eslint-config-next` 16 ships **native flat config arrays**, so the old
 * `FlatCompat(...).extends('next/core-web-vitals')` bridge is no longer used.
 * Keeping it was not merely redundant — it actually crashed with
 * "Converting circular structure to JSON", because FlatCompat re-validates the
 * already-flat plugin objects against the legacy schema and hits a cycle in the
 * React plugin's self-references.
 *
 * ## Why ESLint is pinned to 9
 *
 * `eslint-config-next` 16 declares `eslint: ">=9.0.0"`, and npm happily installs
 * ESLint 10 against that. But every plugin it bundles — react, jsx-a11y,
 * import, and `typescript-eslint` 8 — still declares `^8 || ^9`, and ESLint 10
 * changed the AST scope API in a way they have not caught up with. The symptom
 * is a hard crash, not a warning:
 *
 *     TypeError: scopeManager.addGlobals is not a function
 *
 * So the pin is load-bearing. Raise it only once `eslint-config-next` ships
 * plugins that declare ESLint 10 support.
 */

import typescriptPlugin from '@typescript-eslint/eslint-plugin';
import nextCoreWebVitals from 'eslint-config-next/core-web-vitals';

const config = [
  {
    ignores: [
      '.next/**',
      'node_modules/**',
      // Generated by `prisma generate`. Not ours to lint, and it is rebuilt on
      // every install, so any edit here would be silently discarded.
      'src/generated/**',
      // QA artifacts: screenshots and JSON reports.
      'outputs/**',
      'dist/**',
      'next-env.d.ts',
    ],
  },

  ...nextCoreWebVitals,

  {
    // The TypeScript plugin is re-declared here rather than inherited.
    //
    // In flat config a plugin only exists inside the config objects that
    // declare it, so a rule in a *later* object cannot see a namespace set up
    // in an earlier one. `eslint-config-next` declares `@typescript-eslint` on
    // its own `**/*.ts(x)` entry; without repeating it here, this block fails
    // with "could not find plugin @typescript-eslint".
    files: ['**/*.ts', '**/*.tsx'],
    plugins: { '@typescript-eslint': typescriptPlugin },
    rules: {
      // The brief asks for strict TypeScript. `any` defeats that, and where a
      // cast really is unavoidable the code should say *why* with a narrow
      // type or an inline disable rather than reach for the escape hatch.
      '@typescript-eslint/no-explicit-any': 'error',

      // Unused args are allowed only when prefixed with `_`, which is the
      // convention for "required by the signature, deliberately ignored".
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
        },
      ],
    },
  },

  {
    rules: {
      // `console.warn` and `console.error` are how the fallback layer reports a
      // failed query, and how the contact form reports that it could not send.
      // Silent failures are explicitly forbidden by the brief, so those stay.
      'no-console': ['warn', { allow: ['warn', 'error'] }],
    },
  },

  {
    // CLI scripts are a different environment from the app.
    //
    // `prisma/seed.ts` and `scripts/make-placeholders.ts` are run by a person
    // from a terminal and their whole job is to report progress to that person.
    // Routing their output through `console.warn` to satisfy the app's rule
    // would be cargo-culting the rule into a context it was not written for —
    // and would make real warnings indistinguishable from "✓ 2 program keahlian".
    files: ['prisma/seed.ts', 'scripts/**/*.ts'],
    rules: {
      'no-console': 'off',
    },
  },
];

export default config;
